---
VpcCIDR: 10.88.0.0/16
AvailabilityZones: "ap-southeast-2a,ap-southeast-2b,ap-southeast-2c"
PublicSubnetCIDR: "10.88.0.0/20,10.88.16.0/20,10.88.32.0/20"
PrivateSubnetCIDR: "10.88.64.0/20,10.88.80.0/20,10.88.96.0/20"
VpcFlowLogRetention: '14'
VpcFlowLogTrafficType: ALL
PublicDomainName: semmer-test.dev.com.au.
#BuildKiteVPCId: vpc-985e32fc
