---
VpcCIDR: 192.168.0.0/16
AvailabilityZones: "ap-southeast-2a,ap-southeast-2b,ap-southeast-2c"
PublicSubnetCIDR: "192.168.0.0/20,192.168.16.0/20,192.168.32.0/20"
PrivateSubnetCIDR: "192.168.64.0/20,192.168.80.0/20,192.168.96.0/20"
VpcFlowLogRetention: '14'
VpcFlowLogTrafficType: ALL
PublicDomainName: semmer-test.dev.com.au.
#BuildKiteVPCId: vpc-985e32fc
